#!/usr/bin/env python3

import argparse
import glob
import os
import shutil
import sys


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--dest',
        default='~/Documents/2018/05/k5/site/pub/j/2022/06/20/march-14-2021-2am',
        help="where to write the files")
    args = parser.parse_args()

    dest = os.path.expanduser(args.dest)
    for img in glob.glob('*.svg'):
        shutil.copy(
            img,
            os.path.join(dest, img))


if __name__ == '__main__':
    sys.exit(main())
